services:

  db:
    image: postgres:17.5
    restart: always
    ports:
      - "5432:5432"
    networks:
      - url_shortner
    volumes:
      - url_shortner-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener

  node:
    build: .
    restart: always
    networks:
      - url_shortner
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: url_shortener
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"

  redis:
    image: redis:7
    restart: always
    networks:
      - url_shortner
    ports:
      - "6379:6379"

networks:
  url_shortner:
    driver: bridge

volumes:
  url_shortner-data:
    driver: local
